<?php
// Autogenerated from composer.json - All changes will be overridden if generated again!

require_once __DIR__ . "/vendor/autoload.php";

$id = "xhfp";
$version = "2.6.3";
$ilias_min_version = "5.4.0";
$ilias_max_version = "6.999";
$responsible = "studer + raimann ag - Team Custom 1";
$responsible_mail = "support-custom1@studer-raimann.ch";
